# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=30, verbose_name='主机名称')),
                ('ip', models.GenericIPAddressField(verbose_name='主机IP')),
                ('port', models.IntegerField(verbose_name='主机端口')),
                ('department', models.CharField(max_length=32, verbose_name='部门')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('area', models.CharField(max_length=32, verbose_name='地区')),
                ('onlin_time', models.DateTimeField(verbose_name='上线时间')),
                ('update_time', models.DateTimeField(verbose_name='下线时间')),
                ('description', models.TextField(verbose_name='详细信息')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=32, verbose_name='用户密码')),
                ('email', models.EmailField(max_length=32, verbose_name='邮箱地址')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.UserType'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.UserInfo'),
        ),
    ]
